repos:
-   repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
    - id: black
-   repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8~=7.0.0]
